### ISSUE TITLE
Transition with same from and to values causes error

### ISSUE THREAD

**Issue by ericsartor** [smnh/TransitionJs#1]
When using a transition such as:

  ```
{
    property: 'left',
    from: '560px',
    to: '560px',
    duration: '1s',
    timingFunction: 'linear',
}
```

It results in `this.resolve is not a function` error, which causes the promise to never resolve..  By incrementing the `to` value by 1 pixel, it fixes it.  Why is this happening?

**Comment by smnh** [comment]
Thanks for the report @ericsartor,
This was a bug. Fixed and published under new tag "0.0.7"
